[package]
name = "windotfiles_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
druid-shell = "0.8.3"
nfd = "0.0.4"